services:
  - type: web
    name: video-processor-server
    env: node
    buildCommand: npm install
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
      - src/**/*.ts
      - package.json
      - package-lock.json
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 10